export const bookTypes = [
  "GOSPEL",
  "CHILD",
  "DEVOTIONAL",
  "THEOLOGY",
  "BIBLE_STUDY",
  "CHRISTIAN_FICTION",
  "SPIRITUAL_SELF_HELP",
  "BIOGRAPHY",
  "MISSIONS",
  "CHRISTIAN_EDUCATION",
  "FAMILY",
  "CHRISTIAN_LEADERSHIP",
];
